title: Yichen's Homepage
page-top-title: Yichen Ding（丁熠晨）
top-section-bg-text: Life is an experience that gradually becomes more complete.
home-subtitle: Yichen Ding&ensp;|&ensp;丁熠晨
copyright-text: '&copy; Yichen Ding 2025-2026. All Rights Reserved.'
